api_version = "2026-01"
[[extensions]]
name = "comma discount type"
description = "Pick which offer a comma discount is (free harness, $50 off, or bulk)."
handle = "comma-discount-settings"
uid = "20f699f0-a040-cf87-e71b-a05ea0f48511f9a7e0d6"
type = "ui_extension"
# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"

