# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d99bbfd97a42761e351aa252a06a3664"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "comma discounts"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
