name: Update compatibility
on:
  schedule:
    - cron: '0 0 * * *'  # 4pm PST (midnight UTC)
  workflow_dispatch:

env:
  PR_BRANCH: update-vehicles

jobs:
  update_compatibility:
    name: Update vehicles and harness information
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: commaai/opendbc
          path: opendbc
      - name: Update vehicles and harness information
        run: |
          cd opendbc && source setup.sh && scons -j8
          python ../scripts/compatibility.py
          cd .. && rm -rf opendbc
      - name: Check for meaningful changes
        id: changes
        run: |
          CHANGED_FILES="$(git diff --name-only)"
          echo "$CHANGED_FILES"
          if [ "$(echo "$CHANGED_FILES" | wc -l)" -eq 1 ] && grep -qx 'src/lib/compatibility-meta.json' <<< "$CHANGED_FILES"; then
            echo "skip_pr=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Pull Request
        if: steps.changes.outputs.skip_pr != 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update vehicles and harness information
          title: 'Update vehicles and harness information'
          labels: bot
          branch: ${{ env.PR_BRANCH }}
          base: master
          delete-branch: true
          body: This is an automated PR to update the supported vehicles and harness information, pulled from [commaai/openpilot](https://github.com/commaai/openpilot).
