name: Update compatibility
on:
  # Run every day at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allows you to manually run this workflow from the Actions tab
  workflow_dispatch:

env:
  OPENPILOT_DOCKER: ghcr.io/commaai/openpilot-prebuilt:latest
  PR_BRANCH: update-vehicles

jobs:
  update_compatibility:
    name: Update vehicles and harness information
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Update vehicles and harness information
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/app $OPENPILOT_DOCKER python /app/scripts/compatibility.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@af7c021bb9c41362d0986422bd244ce51a3bf52f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update vehicles and harness information
          title: 'Update vehicles and harness information'
          labels: compatibility
          branch: ${{ env.PR_BRANCH }}
          base: master
          delete-branch: true
          body: This is an automated PR to update the supported vehicles and harness information, pulled from [commaai/openpilot](https://github.com/commaai/openpilot).
